In [1]:
import numpy as np

In [2]:
np.array([34, 23, 23])

array([34, 23, 23])

In [3]:
zeros = np.zeros((2,5))

In [4]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])