In [1]:
import numpy as np

In [10]:
lspace = np.linspace(1, 50, 10)

In [13]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [11]:
emp = np.empty((4, 6))

In [12]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.78145267e-307, 4.45047875e-308, 1.89145368e-307],
       [7.56587584e-307, 1.37961302e-306, 1.05699242e-307,
        8.01097889e-307, 1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 2.78149851e-307, 1.06811422e-306,
        1.78018403e-306, 1.11261095e-306, 6.23057349e-307],
       [1.11260144e-306, 1.78021798e-306, 1.20161526e-306,
        6.89805151e-307, 1.78020169e-306, 1.42410974e-306]])

In [14]:
emp_like = np.empty_like(lspace)

In [15]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])