In [1]:
import numpy as np

In [2]:
x = [[1,2,3,], [4, 5, 6,], [7, 8, 4]]

In [3]:
ar = np.array(x)

In [4]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 4]])

In [5]:
ar.sum(axis=0)

array([12, 15, 13])

In [6]:
ar.sum(axis=1)

array([ 6, 15, 19])

In [7]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 4]])

In [8]:
ar.flat

In [10]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
4


In [11]:
ar.ndim

2

In [12]:
ar.size

9

In [13]:
ar.shape

(3, 3)

In [14]:
ar.dtype

dtype('int64')

In [16]:
ar.nbytes

72

In [18]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 4]])

In [20]:
ar.argmin()

np.int64(0)

In [21]:
ar.argmax()

np.int64(7)

In [22]:
ar.argmax(axis=0)

array([2, 2, 1])

In [23]:
ar.argmax(axis=1)

array([2, 2, 1])

In [25]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 2],
       [2, 2, 1]])

In [26]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]])

In [27]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 4]])

In [28]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 4])

In [34]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 8, 4])

In [35]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [4]])

In [36]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 4]])

In [37]:
ar2 = np.array([[1, 2, 1],
                [4, 0, 6],
                [8, 1, 0]])

In [38]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [39]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  9,  4]])

In [40]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  8,  0]])

In [42]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 2.        ]])

In [43]:
ar.sum()


np.int64(40)

In [44]:
ar.min()

np.int64(1)

In [45]:
ar.max()

np.int64(8)

In [46]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 4]])

In [49]:
np.where(ar>5)

(array([1, 2, 2]), array([2, 0, 1]))

In [50]:
type(np.where(ar>5))

tuple

In [52]:
np.count_nonzero(ar)

np.int64(9)

In [53]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [54]:
import sys

In [55]:
py_ar = [0, 4, 55,2]

In [57]:
np_ar = np.array(py_ar)

In [58]:
sys.getsizeof(1) * len(py_ar)

112

In [59]:
np_ar.itemsize * np_ar.size

32

In [60]:
np_ar.tolist()

[0, 4, 55, 2]